r= ("\n"
    "Switching on camera from habitat with camels...\n"
    " ___.-''''-.\n"
    "/___  @    |\n"
    "',,,,.     |         _.'''''''._\n"
    "     '     |        /           \\n"
    "     |     \    _.-'             \\n"
    "     |      '.-'                  '-.\n"
    "     |                               ',\n"
    "     |                                '',\n"
    "      ',,-,                           ':;\n"
    "           ',,| ;,,                 ,' ;;\n"
    "              ! ; !'',,,',',,,,'!  ;   ;:\n"
    "             : ;  ! !       ! ! ;  ;   :;\n"
    "             ; ;   ! !      ! !  ; ;   ;,\n"
    "            ; ;    ! !     ! !   ; ;     \n"
    "            ; ;    ! !    ! !     ; ;\n"
    "           ;,,      !,!   !,!     ;,;\n"
    "           /_I      L_I   L_I     /_I\n"
    "Yey, our little camel is sunbathing!")

print(r)
